server:
  port: 8080
spring:
  application:
    name: banana-export
  h2:
    console:
      enabled: true
      path: /banana-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:banana-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true